[2023-05-03T19:41:39.145+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.extract_data_gcp scheduled__2023-05-03T19:30:00+00:00 [queued]>
[2023-05-03T19:41:39.150+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.extract_data_gcp scheduled__2023-05-03T19:30:00+00:00 [queued]>
[2023-05-03T19:41:39.150+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-03T19:41:39.150+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-03T19:41:39.150+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-03T19:41:39.160+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): extract_data_gcp> on 2023-05-03 19:30:00+00:00
[2023-05-03T19:41:39.163+0000] {standard_task_runner.py:55} INFO - Started process 225674 to run task
[2023-05-03T19:41:39.165+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dag', 'extract_data_gcp', 'scheduled__2023-05-03T19:30:00+00:00', '--job-id', '2710', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpn9pd4v36']
[2023-05-03T19:41:39.166+0000] {standard_task_runner.py:83} INFO - Job 2710: Subtask extract_data_gcp
[2023-05-03T19:41:39.195+0000] {task_command.py:389} INFO - Running <TaskInstance: etl_dag.extract_data_gcp scheduled__2023-05-03T19:30:00+00:00 [running]> on host trivia-machine.us-central1-a.c.triviapractice-381517.internal
[2023-05-03T19:41:39.230+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=richc
AIRFLOW_CTX_DAG_ID=etl_dag
AIRFLOW_CTX_TASK_ID=extract_data_gcp
AIRFLOW_CTX_EXECUTION_DATE=2023-05-03T19:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-03T19:30:00+00:00
[2023-05-03T19:41:39.231+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.9/dist-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/rich2/airflow/dags/etl_dag.py", line 35, in extract_data_gcp
    bucket = storage_client.get_bucket(bucket_name)
NameError: name 'storage_client' is not defined
[2023-05-03T19:41:39.233+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=etl_dag, task_id=extract_data_gcp, execution_date=20230503T193000, start_date=20230503T194139, end_date=20230503T194139
[2023-05-03T19:41:39.242+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 2710 for task extract_data_gcp (name 'storage_client' is not defined; 225674)
[2023-05-03T19:41:39.257+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-03T19:41:39.268+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
